<a href="https://colab.research.google.com/github/seeedata/BADA/blob/main/BADATON/%EC%A7%80%ED%95%98%EC%B2%A0%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%A0%84%EC%B2%98%EB%A6%AC%20%EA%B7%80%EA%B0%80%EC%8B%9C%EA%B0%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

#데이터 불러오기

In [3]:
subway = pd.read_csv('/content/drive/MyDrive/BADA/바다톤/data/서울시 지하철 호선별 역별 시간대별 승하차 인원 정보_바다톤.csv', index_col=False, encoding='cp949')
subway

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,202306,1호선,동대문,854,33,11997,2157,9533,7157,14547,...,9146,624,2562,3,247,0,0,0,0,20230703
1,202306,1호선,동묘앞,228,2,3088,1143,3886,5140,7501,...,4379,111,1761,0,331,0,0,0,0,20230703
2,202306,1호선,서울역,677,33,8470,9569,13528,54052,44183,...,14949,2554,2856,0,229,0,0,0,0,20230703
3,202306,1호선,시청,61,1,2351,4528,3862,24513,7856,...,4535,334,1075,0,36,1,0,0,0,20230703
4,202306,1호선,신설동,494,24,9258,2481,9513,8392,22078,...,9722,434,2294,1,0,1,0,0,0,20230703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60017,201501,중앙선,운길산,0,0,177,56,642,403,1292,...,633,3,222,0,0,0,0,0,0,20151223
60018,201501,중앙선,원덕,1,0,292,4,415,46,537,...,383,3,157,0,0,0,0,0,0,20151223
60019,201501,중앙선,중랑,14,1,4929,424,8539,2084,22160,...,6501,86,1617,0,0,0,0,0,0,20151223
60020,201501,중앙선,팔당,0,0,161,50,368,149,1227,...,336,8,85,0,0,0,0,0,0,20151223
60021,201501,중앙선,회기,436,3,10929,3067,23317,10430,65043,...,35702,767,9314,0,0,0,0,0,0,20151223

In [4]:
subway.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60022 entries, 0 to 60021
Data columns (total 52 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   사용월           60022 non-null  int64
 1   호선명           60022 non-null  object
 2   지하철역          60022 non-null  object
 3   04시-05시 승차인원  60022 non-null  int64
 4   04시-05시 하차인원  60022 non-null  int64
 5   05시-06시 승차인원  60022 non-null  int64
 6   05시-06시 하차인원  60022 non-null  int64
 7   06시-07시 승차인원  60022 non-null  int64
 8   06시-07시 하차인원  60022 non-null  int64
 9   07시-08시 승차인원  60022 non-null  int64
 10  07시-08시 하차인원  60022 non-null  int64
 11  08시-09시 승차인원  60022 non-null  int64
 12  08시-09시 하차인원  60022 non-null  int64
 13  09시-10시 승차인원  60022 non-null  int64
 14  09시-10시 하차인원  60022 non-null  int64
 15  10시-11시 승차인원  60022 non-null  int64
 16  10시-11시 하차인원  60022 non-null  int64
 17  11시-12시 승차인원  60022 non-null  int64
 18  11시-12시 하차인원  60022 non-null  int64
 19  12시-13시 승차인원  60022 non-null  int64
 20  12시-13시 하차인원  60022 non-null  int64
 21  13시-14시 승차인원  60022 non-null  int64
 22  13시-14시 하차인원  60022 non-null  int64
 23  14시-15시 승차인원  60022 non-null  int64
 24  14시-15시 하차인원  60022 non-null  int64
 25  15시-16시 승차인원  60022 non-null  int64
 26  15시-16시 하차인원  60022 non-null  int64
 27  16시-17시 승차인원  60022 non-null  int64
 28  16시-17시 하차인원  60022 non-null  int64
 29  17시-18시 승차인원  60022 non-null  int64
 30  17시-18시 하차인원  60022 non-null  int64
 31  18시-19시 승차인원  60022 non-null  int64
 32  18시-19시 하차인원  60022 non-null  int64
 33  19시-20시 승차인원  60022 non-null  int64
 34  19시-20시 하차인원  60022 non-null  int64
 35  20시-21시 승차인원  60022 non-null  int64
 36  20시-21시 하차인원  60022 non-null  int64
 37  21시-22시 승차인원  60022 non-null  int64
 38  21시-22시 하차인원  60022 non-null  int64
 39  22시-23시 승차인원  60022 non-null  int64
 40  22시-23시 하차인원  60022 non-null  int64
 41  23시-24시 승차인원  60022 non-null  int64
 42  23시-24시 하차인원  60022 non-null  int64
 43  00시-01시 승차인원  60022 non-null  int64
 44  00시-01시 하차인원  60022 non-null  int64
 45  01시-02시 승차인원  60022 non-null  int64
 46  01시-02시 하차인원  60022 non-null  int64
 47  02시-03시 승차인원  60022 non-null  int64
 48  02시-03시 하차인원  60022 non-null  int64
 49  03시-04시 승차인원  60022 non-null  int64
 50  03시-04시 하차인원  60022 non-null  int64
 51  작업일자          60022 non-null  int64
dtypes: int64(50), object(2)
memory usage: 23.8+ MB

In [5]:
subway.columns

Index(['사용월', '호선명', '지하철역', '04시-05시 승차인원', '04시-05시 하차인원', '05시-06시 승차인원',
       '05시-06시 하차인원', '06시-07시 승차인원', '06시-07시 하차인원', '07시-08시 승차인원',
       '07시-08시 하차인원', '08시-09시 승차인원', '08시-09시 하차인원', '09시-10시 승차인원',
       '09시-10시 하차인원', '10시-11시 승차인원', '10시-11시 하차인원', '11시-12시 승차인원',
       '11시-12시 하차인원', '12시-13시 승차인원', '12시-13시 하차인원', '13시-14시 승차인원',
       '13시-14시 하차인원', '14시-15시 승차인원', '14시-15시 하차인원', '15시-16시 승차인원',
       '15시-16시 하차인원', '16시-17시 승차인원', '16시-17시 하차인원', '17시-18시 승차인원',
       '17시-18시 하차인원', '18시-19시 승차인원', '18시-19시 하차인원', '19시-20시 승차인원',
       '19시-20시 하차인원', '20시-21시 승차인원', '20시-21시 하차인원', '21시-22시 승차인원',
       '21시-22시 하차인원', '22시-23시 승차인원', '22시-23시 하차인원', '23시-24시 승차인원',
       '23시-24시 하차인원', '00시-01시 승차인원', '00시-01시 하차인원', '01시-02시 승차인원',
       '01시-02시 하차인원', '02시-03시 승차인원', '02시-03시 하차인원', '03시-04시 승차인원',
       '03시-04시 하차인원', '작업일자'],
      dtype='object')

In [6]:
#날짜 추출
subway = subway[(subway['사용월']>=202212) & (subway['사용월']<=202303)]
#열 제거
subway = subway[['사용월', '호선명', '지하철역', '04시-05시 하차인원', '18시-19시 하차인원', '19시-20시 하차인원', '20시-21시 하차인원',
       '21시-22시 하차인원', '22시-23시 하차인원', '23시-24시 하차인원', '00시-01시 하차인원',  '01시-02시 하차인원',  '02시-03시 하차인원',
       '03시-04시 하차인원']]
subway

,사용월,호선명,지하철역,04시-05시 하차인원,18시-19시 하차인원,19시-20시 하차인원,20시-21시 하차인원,21시-22시 하차인원,22시-23시 하차인원,23시-24시 하차인원,00시-01시 하차인원,01시-02시 하차인원,02시-03시 하차인원,03시-04시 하차인원
1841,202303,1호선,동대문,8,22150,21176,14561,12652,11596,8898,2612,247,0,0
1842,202303,1호선,동묘앞,2,12211,8498,5990,5993,6606,4133,1587,299,0,0
1843,202303,1호선,서울역,35,99606,68805,47220,41748,28916,14624,3091,220,0,0
1844,202303,1호선,시청,0,27244,14072,9281,8987,6923,4654,1076,27,1,0
1845,202303,1호선,신설동,11,32909,23490,15187,14401,12878,9422,2110,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4291,202212,중앙선,원덕,0,819,688,479,544,313,272,75,0,0,0
4292,202212,중앙선,중랑,2,21037,16622,10887,8478,9557,5299,411,0,0,0
4293,202212,중앙선,지평,0,151,233,1,95,63,0,0,0,0,0
4294,202212,중앙선,팔당,0,1650,965,593,516,489,218,0,0,0,0
4295,202212,중앙선,회기,8,78819,60601,39336,38893,43867,29198,5434,167,0,0

In [7]:
#역명
stations = [
            '잠실나루', '잠실(송파구청)', '잠실새내', '종합운동장', '가락시장', '경찰병원', '오금', '올림픽공원(한국체대)', '방이', '개롱', '거여', '마천', '몽촌토성(평화의문)', '석촌', '송파', '문정', '장지', '복정', '삼전', '석촌고분', '송파나루', '한성백제',
            '방화', '개화산', '김포공항', '송정', '마곡', '발산', '우장산', '화곡', '까치산', '개화', '공항시장', '신방화', '마곡나루(서울식물원)', '양천향교', '가양', '증미', '등촌',
            '삼성(무역센터)', '선릉', '역삼', '강남', '압구정', '신사', '매봉', '도곡', '대치', '학여울', '대청', '일원', '수서', '청담', '강남구청', '학동', '논현', '언주', '선정릉', '삼성중앙', '봉은사', '신논현', '압구정로데오', '한티', '구룡', '개포동', '대모산입구',
            '당고개', '상계', '노원', '석계', '태릉입구', '화랑대(서울여대입구)', '수락산', '마들', '중계', '하계', '공릉(서울과학기술대)', '월계', '광운대',
            '낙성대(강감찬)', '서울대입구(관악구청)', '봉천', '신림', '당곡', '서원', '서울대벤처타운', '관악산(서울대)'
            ]

In [8]:
subway = subway.loc[subway['지하철역'].isin(stations)] ; subway

,사용월,호선명,지하철역,04시-05시 하차인원,18시-19시 하차인원,19시-20시 하차인원,20시-21시 하차인원,21시-22시 하차인원,22시-23시 하차인원,23시-24시 하차인원,00시-01시 하차인원,01시-02시 하차인원,02시-03시 하차인원,03시-04시 하차인원
1851,202303,2호선,강남,4,192553,117295,60236,47709,40835,25158,7593,51,0,0
1857,202303,2호선,낙성대(강감찬),0,106169,94866,59829,56458,57379,36166,10215,129,0,0
1865,202303,2호선,봉천,5,91477,80321,48869,45952,44374,26772,8596,411,0,0
1867,202303,2호선,삼성(무역센터),1,64759,37607,19084,15492,12361,7033,4343,1190,0,0
1869,202303,2호선,서울대입구(관악구청),36,184437,156541,94060,87179,88251,52433,20082,3521,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4220,202212,신림선,관악산(서울대),1,3943,3190,2206,1810,2078,1410,753,65,0,0
4221,202212,신림선,당곡,0,16140,12007,7024,6321,5888,3986,1388,18,0,0
4227,202212,신림선,서울대벤처타운,0,29370,23873,14981,14057,14073,10310,5045,194,0,0
4229,202212,신림선,서원,0,11009,10406,6573,6144,6181,4480,1762,36,0,0
4230,202212,신림선,신림,0,10378,6837,3779,3563,2911,2053,758,13,0,0

In [9]:
subway.isnull().sum()

사용월             0
호선명             0
지하철역            0
04시-05시 하차인원    0
18시-19시 하차인원    0
19시-20시 하차인원    0
20시-21시 하차인원    0
21시-22시 하차인원    0
22시-23시 하차인원    0
23시-24시 하차인원    0
00시-01시 하차인원    0
01시-02시 하차인원    0
02시-03시 하차인원    0
03시-04시 하차인원    0
dtype: int64

In [10]:
stations_송파 = ['잠실나루', '잠실(송파구청)', '잠실새내', '종합운동장', '가락시장', '경찰병원', '오금', '올림픽공원(한국체대)', '방이', '개롱', '거여', '마천', '몽촌토성(평화의문)', '석촌', '송파', '문정', '장지', '복정', '삼전', '석촌고분', '송파나루', '한성백제']
stations_강서 = ['방화', '개화산', '김포공항', '송정', '마곡', '발산', '우장산', '화곡', '까치산', '개화', '공항시장', '신방화', '마곡나루(서울식물원)', '양천향교', '가양', '증미', '등촌']
stations_강남 = ['삼성(무역센터)', '선릉', '역삼', '강남', '압구정', '신사', '매봉', '도곡', '대치', '학여울', '대청', '일원', '수서', '청담', '강남구청', '학동', '논현', '언주', '선정릉', '삼성중앙', '봉은사', '신논현', '압구정로데오', '한티', '구룡', '개포동', '대모산입구']
stations_노원 = ['당고개', '상계', '노원', '석계', '태릉입구', '화랑대(서울여대입구)', '수락산', '마들', '중계', '하계', '공릉(서울과학기술대)', '월계', '광운대']
stations_관악 = ['낙성대(강감찬)', '서울대입구(관악구청)', '봉천', '신림', '당곡', '서원', '서울대벤처타운', '관악산(서울대)']

In [11]:
subway.loc[subway['지하철역'].isin(stations_송파), 'area'] = '송파구'
subway.loc[subway['지하철역'].isin(stations_강서), 'area'] = '강서구'
subway.loc[subway['지하철역'].isin(stations_강남), 'area'] = '강남구'
subway.loc[subway['지하철역'].isin(stations_노원), 'area'] = '노원구'
subway.loc[subway['지하철역'].isin(stations_관악), 'area'] = '관악구'
subway

<ipython-input-11-2837bc6cba12>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subway.loc[subway['지하철역'].isin(stations_송파), 'area'] = '송파구'

,사용월,호선명,지하철역,04시-05시 하차인원,18시-19시 하차인원,19시-20시 하차인원,20시-21시 하차인원,21시-22시 하차인원,22시-23시 하차인원,23시-24시 하차인원,00시-01시 하차인원,01시-02시 하차인원,02시-03시 하차인원,03시-04시 하차인원,area
1851,202303,2호선,강남,4,192553,117295,60236,47709,40835,25158,7593,51,0,0,강남구
1857,202303,2호선,낙성대(강감찬),0,106169,94866,59829,56458,57379,36166,10215,129,0,0,관악구
1865,202303,2호선,봉천,5,91477,80321,48869,45952,44374,26772,8596,411,0,0,관악구
1867,202303,2호선,삼성(무역센터),1,64759,37607,19084,15492,12361,7033,4343,1190,0,0,강남구
1869,202303,2호선,서울대입구(관악구청),36,184437,156541,94060,87179,88251,52433,20082,3521,0,0,관악구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4220,202212,신림선,관악산(서울대),1,3943,3190,2206,1810,2078,1410,753,65,0,0,관악구
4221,202212,신림선,당곡,0,16140,12007,7024,6321,5888,3986,1388,18,0,0,관악구
4227,202212,신림선,서울대벤처타운,0,29370,23873,14981,14057,14073,10310,5045,194,0,0,관악구
4229,202212,신림선,서원,0,11009,10406,6573,6144,6181,4480,1762,36,0,0,관악구
4230,202212,신림선,신림,0,10378,6837,3779,3563,2911,2053,758,13,0,0,관악구

In [12]:
subway.isnull().sum()

사용월             0
호선명             0
지하철역            0
04시-05시 하차인원    0
18시-19시 하차인원    0
19시-20시 하차인원    0
20시-21시 하차인원    0
21시-22시 하차인원    0
22시-23시 하차인원    0
23시-24시 하차인원    0
00시-01시 하차인원    0
01시-02시 하차인원    0
02시-03시 하차인원    0
03시-04시 하차인원    0
area            0
dtype: int64

In [13]:
subway.columns = ['month', 'station_num', 'station_name', '04-05', '18-19', '19-20', '20-21', '21-22', '22-23', '23-24', '00-01', '01-02', '02-03', '03-04', 'area']
subway

,month,station_num,station_name,04-05,18-19,19-20,20-21,21-22,22-23,23-24,00-01,01-02,02-03,03-04,area
1851,202303,2호선,강남,4,192553,117295,60236,47709,40835,25158,7593,51,0,0,강남구
1857,202303,2호선,낙성대(강감찬),0,106169,94866,59829,56458,57379,36166,10215,129,0,0,관악구
1865,202303,2호선,봉천,5,91477,80321,48869,45952,44374,26772,8596,411,0,0,관악구
1867,202303,2호선,삼성(무역센터),1,64759,37607,19084,15492,12361,7033,4343,1190,0,0,강남구
1869,202303,2호선,서울대입구(관악구청),36,184437,156541,94060,87179,88251,52433,20082,3521,0,0,관악구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4220,202212,신림선,관악산(서울대),1,3943,3190,2206,1810,2078,1410,753,65,0,0,관악구
4221,202212,신림선,당곡,0,16140,12007,7024,6321,5888,3986,1388,18,0,0,관악구
4227,202212,신림선,서울대벤처타운,0,29370,23873,14981,14057,14073,10310,5045,194,0,0,관악구
4229,202212,신림선,서원,0,11009,10406,6573,6144,6181,4480,1762,36,0,0,관악구
4230,202212,신림선,신림,0,10378,6837,3779,3563,2911,2053,758,13,0,0,관악구

In [14]:
subway = subway.reset_index(drop=True); subway

,month,station_num,station_name,04-05,18-19,19-20,20-21,21-22,22-23,23-24,00-01,01-02,02-03,03-04,area
0,202303,2호선,강남,4,192553,117295,60236,47709,40835,25158,7593,51,0,0,강남구
1,202303,2호선,낙성대(강감찬),0,106169,94866,59829,56458,57379,36166,10215,129,0,0,관악구
2,202303,2호선,봉천,5,91477,80321,48869,45952,44374,26772,8596,411,0,0,관악구
3,202303,2호선,삼성(무역센터),1,64759,37607,19084,15492,12361,7033,4343,1190,0,0,강남구
4,202303,2호선,서울대입구(관악구청),36,184437,156541,94060,87179,88251,52433,20082,3521,0,0,관악구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,202212,신림선,관악산(서울대),1,3943,3190,2206,1810,2078,1410,753,65,0,0,관악구
423,202212,신림선,당곡,0,16140,12007,7024,6321,5888,3986,1388,18,0,0,관악구
424,202212,신림선,서울대벤처타운,0,29370,23873,14981,14057,14073,10310,5045,194,0,0,관악구
425,202212,신림선,서원,0,11009,10406,6573,6144,6181,4480,1762,36,0,0,관악구
426,202212,신림선,신림,0,10378,6837,3779,3563,2911,2053,758,13,0,0,관악구

In [15]:
subway = subway[['month', 'area', 'station_num', 'station_name', '18-19', '19-20', '20-21', '21-22', '22-23', '23-24', '00-01', '01-02', '02-03', '03-04', '04-05']]
subway

,month,area,station_num,station_name,18-19,19-20,20-21,21-22,22-23,23-24,00-01,01-02,02-03,03-04,04-05
0,202303,강남구,2호선,강남,192553,117295,60236,47709,40835,25158,7593,51,0,0,4
1,202303,관악구,2호선,낙성대(강감찬),106169,94866,59829,56458,57379,36166,10215,129,0,0,0
2,202303,관악구,2호선,봉천,91477,80321,48869,45952,44374,26772,8596,411,0,0,5
3,202303,강남구,2호선,삼성(무역센터),64759,37607,19084,15492,12361,7033,4343,1190,0,0,1
4,202303,관악구,2호선,서울대입구(관악구청),184437,156541,94060,87179,88251,52433,20082,3521,0,0,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,202212,관악구,신림선,관악산(서울대),3943,3190,2206,1810,2078,1410,753,65,0,0,1
423,202212,관악구,신림선,당곡,16140,12007,7024,6321,5888,3986,1388,18,0,0,0
424,202212,관악구,신림선,서울대벤처타운,29370,23873,14981,14057,14073,10310,5045,194,0,0,0
425,202212,관악구,신림선,서원,11009,10406,6573,6144,6181,4480,1762,36,0,0,0
426,202212,관악구,신림선,신림,10378,6837,3779,3563,2911,2053,758,13,0,0,0

In [16]:
subway_group = subway.groupby(['month', 'area']).sum(); subway_group

<ipython-input-16-3eeefa3e9209>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  subway_group = subway.groupby(['month', 'area']).sum(); subway_group

               18-19   19-20   20-21   21-22   22-23   23-24  00-01  01-02  \
month  area
202212 강남구   1269443  780075  441946  398893  346778  204190  65108   4356
       강서구    763937  594207  351796  322654  300223  197045  67904   2346
       관악구    650498  566016  350287  337372  334298  216864  72212   6551
       노원구    689293  606052  355646  322886  300443  211041  70805   3887
       송파구   1064002  739614  444658  416893  399304  239929  70742   3274
202301 강남구   1096686  700185  394025  339075  295314  171098  52947   2905
       강서구    714265  577892  329766  293491  262660  165127  55445   1408
       관악구    611444  552779  330721  310472  294234  186375  61051   4652
       노원구    634638  582127  326954  288659  259498  179953  59495   3088
       송파구    936088  676095  399624  358353  340256  198218  57570   1999
202302 강남구   1127518  726608  402482  345184  302767  174112  54892   2684
       강서구    725751  583538  336125  293681  269106  171275  58633   1119
       관악구    612010  558109  333721  308966  298864  189790  64981   4365
       노원구    648633  590472  335271  296664  268222  183363  62440   2820
       송파구    945968  690808  409648  372307  350814  203673  60689   1793
202303 강남구   1237088  807585  455128  389655  350018  200514  63782   3006
       강서구    799745  644385  381079  335112  305593  192289  64949   1238
       관악구    699462  611896  376680  353871  343957  217771  74073   4749
       노원구    745806  661989  383577  336767  310923  209609  71754   3467
       송파구   1065575  782650  463414  417759  399159  228622  68268   1752

             02-03  03-04  04-05
month  area
202212 강남구     335    219     68
       강서구     218     45      5
       관악구     457    182     46
       노원구      41      0     62
       송파구     299     24     23
202301 강남구      83      0     63
       강서구      62      0      8
       관악구      51      0     29
       노원구      17      0     51
       송파구      37      0     20
202302 강남구       2      0     28
       강서구       1      0      5
       관악구       1      0     39
       노원구       0      0     60
       송파구       3      0     20
202303 강남구       0      0     46
       강서구       8      0      8
       관악구       0      0     52
       노원구       0      0     57
       송파구       2      0     31

In [17]:
subway_group.to_csv('/content/drive/MyDrive/BADA/바다톤/data/귀가시간대_지하철_하차인원_통합.csv')