<a href="https://colab.research.google.com/github/seeedata/BADA/blob/main/%ED%96%89%EC%82%AC%20%EC%B0%B8%EC%97%AC%20%EC%9D%B8%EC%9B%90%20%EC%98%88%EC%B8%A1%EC%9D%84%20%ED%86%B5%ED%95%9C%20%EC%95%88%EC%A0%84%20%EA%B4%80%EB%A6%AC%20%EC%BB%A8%EC%84%A4%ED%8C%85%20%EC%84%9C%EB%B9%84%EC%8A%A4/0713%20%ED%96%89%EC%82%AC%20data%20%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KS_OLPARK_RENT_INFO_202303.csv')
df

,RENTLSPCE_PLACE_NM,RENTLSPCE_HOUR_DC,FCLTY_NM,FCLTY_ABRV_NM,EVENT_SDIV_NM,EVENT_NM,RENTLSPCE_BEGIN_DE,RENTLSPCE_END_DE,USE_DAY_CO,REQST_EVENT_NMPR_CO,EXCCLC_EVENT_NMPR_CO,PLNNN_RENTLSPCE_AT,ISE_ELSE_FLAG_NM
0,1,7,우리금융아트홀,제3체육관,체육행사,7330노인건강체조경연대회,20150917,20150917,1.0,550.0,NaN,NaN,내부
1,1,9,올림픽홀,올림픽홀,대중공연,김우빈 팬미팅,20161002,20161003,2.0,0.0,1410.0,N,내부
2,1,7,우리금융아트홀,제3체육관,문화예술행사,나무야나무야(8월),20160801,20160831,31.0,NaN,2658.0,Y,내부
3,1,3,KSPO DOME(체조경기장),제1체육관,문화예술행사,Angels Giving Hope 2016 콘서트,20160922,20160923,2.0,6000.0,366.0,N,내부
4,1,5,핸드볼경기장,핸드볼경기장,문화예술행사,트와이스 콘서트,20170213,20170219,6.0,8000.0,11924.0,N,내부
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3947,1,19,평화의광장,평화의광장,공공행사,2023 서울마라톤 겸 동아마라톤,20230318,20230319,2.0,10000.0,10000.0,N,외부
3948,1,7,우리금융아트홀,제3체육관,순수예술공연,제 39회 KUCO 정기연주회,20230304,20230304,1.0,0.0,NaN,N,내부
3949,1,5,핸드볼경기장,핸드볼경기장,문화예술행사,대우건설 창립50주년 기념 축하콘서트(KBS 열린음악회),20230319,20230325,7.0,4.0,NaN,N,내부
3950,1,9,올림픽홀,올림픽홀,문화예술행사,2023 장윤정 단독 콘서트,20230221,20230225,5.0,0.0,NaN,N,내부
3951,1,3,KSPO DOME(체조경기장),제1체육관,문화예술행사,투모로우바이투게더 2023 콘서트,20230321,20230327,7.0,25000.0,NaN,N,내부

##### Column 설명

FCLTY_NM: 시설명

EVENT_SDIV_NM: 행사 구분명

EVENT_NM: 행사명

RENTLSPCE_BEGIN_DE: 대관시작일자

RENTLSPCE_END_DE: 대관종료일자

USE_DAY_CO: 사용일수

REQST_EVENT_NMPR_CO: 신청행사인원수

EXCCLC_EVENT_NMPR_CO: 정산행사인원수

ISE_ELSE_FLAG_NM: 내외구분명

In [ ]:
df = df.drop(df.columns[[0,1,3,11]], axis=1)

1. 날짜정렬

- 행사 시작 시점으로 오름차순 정렬

In [ ]:
df = df.sort_values("RENTLSPCE_BEGIN_DE")
df

,FCLTY_NM,EVENT_SDIV_NM,EVENT_NM,RENTLSPCE_BEGIN_DE,RENTLSPCE_END_DE,USE_DAY_CO,REQST_EVENT_NMPR_CO,EXCCLC_EVENT_NMPR_CO,ISE_ELSE_FLAG_NM
454,한얼광장,공공행사,제13회 베이징장애인올림픽대회 선전기원 2008 Friendly Festival,20080821,20080822,2.0,500.0,0.0,외부
447,88잔디마당,대중공연,2008 제2회 Let's Rock Festival,20080904,20080906,3.0,15000.0,0.0,외부
2157,한얼광장,공공행사,기탁자는 기쁨을..이용자는 희망을! 2008 식품나눔행사,20081015,20081015,1.0,500.0,0.0,외부
445,올림픽홀,대중공연,큐반 올스타 콘서트,20081107,20081108,2.0,3000.0,0.0,내부
2158,KSPO DOME(체조경기장),문화예술행사,플라시도 도밍고 내한공연,20090111,20090113,3.0,10000.0,0.0,내부
...,...,...,...,...,...,...,...,...,...
3933,뮤즈라이브,문화예술행사,2023 프렌쥬 신비의 손전등,20230327,20230423,28.0,7600.0,NaN,내부
3942,KSPO DOME(체조경기장),문화예술행사,Red Velvet 4th CONCERT,20230328,20230403,7.0,16000.0,NaN,내부
3945,올림픽홀,문화예술행사,2023 권진아 단독 콘서트,20230328,20230402,6.0,7500.0,NaN,내부
3944,핸드볼경기장,문화예술행사,2023 SG워너비 콘서트,20230329,20230402,5.0,206.0,NaN,내부
3941,우리금융아트홀,대중공연,"정여진 & TULA anisong concert, HAPPY ENDING",20230331,20230401,2.0,1000.0,NaN,내부

2. 신청, 정산인원 둘 다 결측치이거나 0인 행 drop 하기

In [ ]:
df.isnull().sum()

FCLTY_NM                   0
EVENT_SDIV_NM              9
EVENT_NM                   0
RENTLSPCE_BEGIN_DE         0
RENTLSPCE_END_DE           0
USE_DAY_CO               158
REQST_EVENT_NMPR_CO      174
EXCCLC_EVENT_NMPR_CO    1762
ISE_ELSE_FLAG_NM           0
dtype: int64

In [ ]:
# 공연구분 정의 안된 행 drop
df = df[~ df["EVENT_SDIV_NM"].isnull()]

In [ ]:
from datetime import datetime

In [ ]:
df["RENTLSPCE_BEGIN_DE"]= df["RENTLSPCE_BEGIN_DE"].astype('str')

In [ ]:
df["RENTLSPCE_END_DE"]= df["RENTLSPCE_END_DE"].astype('str')

In [ ]:
df["RENTLSPCE_BEGIN_DE"] = pd.to_datetime(df["RENTLSPCE_BEGIN_DE"])

In [ ]:
df["RENTLSPCE_END_DE"] = pd.to_datetime(df["RENTLSPCE_END_DE"])

In [ ]:
# 사용일수 계산 (종료일자-시작일자 +1)
diff = df["RENTLSPCE_END_DE"]- df["RENTLSPCE_BEGIN_DE"]
df["USE_DAY_CO"] = diff
df

<ipython-input-43-9e16d0b41ddd>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["USE_DAY_CO"] = diff

,FCLTY_NM,EVENT_SDIV_NM,EVENT_NM,RENTLSPCE_BEGIN_DE,RENTLSPCE_END_DE,USE_DAY_CO,REQST_EVENT_NMPR_CO,EXCCLC_EVENT_NMPR_CO,ISE_ELSE_FLAG_NM
454,한얼광장,공공행사,제13회 베이징장애인올림픽대회 선전기원 2008 Friendly Festival,20080821,20080822,2,500.0,0.0,외부
447,88잔디마당,대중공연,2008 제2회 Let's Rock Festival,20080904,20080906,3,15000.0,0.0,외부
2157,한얼광장,공공행사,기탁자는 기쁨을..이용자는 희망을! 2008 식품나눔행사,20081015,20081015,1,500.0,0.0,외부
445,올림픽홀,대중공연,큐반 올스타 콘서트,20081107,20081108,2,3000.0,0.0,내부
2158,KSPO DOME(체조경기장),문화예술행사,플라시도 도밍고 내한공연,20090111,20090113,3,10000.0,0.0,내부
...,...,...,...,...,...,...,...,...,...
3933,뮤즈라이브,문화예술행사,2023 프렌쥬 신비의 손전등,20230327,20230423,97,7600.0,NaN,내부
3942,KSPO DOME(체조경기장),문화예술행사,Red Velvet 4th CONCERT,20230328,20230403,76,16000.0,NaN,내부
3945,올림픽홀,문화예술행사,2023 권진아 단독 콘서트,20230328,20230402,75,7500.0,NaN,내부
3944,핸드볼경기장,문화예술행사,2023 SG워너비 콘서트,20230329,20230402,74,206.0,NaN,내부
3941,우리금융아트홀,대중공연,"정여진 & TULA anisong concert, HAPPY ENDING",20230331,20230401,71,1000.0,NaN,내부

In [ ]:
len(df.dropna(subset=["REQST_EVENT_NMPR_CO", "EXCCLC_EVENT_NMPR_CO"]))

2106

In [ ]:
len(df[(df["REQST_EVENT_NMPR_CO"] != 0) | (df["EXCCLC_EVENT_NMPR_CO"] != 0)])

3902

In [ ]:
# 신청인원, 정산인원 결측치인 행 제거
df = df.dropna(subset=["REQST_EVENT_NMPR_CO", "EXCCLC_EVENT_NMPR_CO"])

In [ ]:
# 신청인원, 정산인원 0인 행 제거
df = df[(df["REQST_EVENT_NMPR_CO"] != 0) | (df["EXCCLC_EVENT_NMPR_CO"] != 0)]

In [ ]:
df.shape # 495개의 행

(2065, 9)

In [ ]:
#인덱스 재정렬
df.reset_index(drop=True, inplace =True)

3. 훈련 등 관련없는 word 제외

In [ ]:
index = df[df["EVENT_NM"].str.contains("훈련")].index

In [ ]:
df.drop(index, inplace=True)

In [ ]:
df

,FCLTY_NM,EVENT_SDIV_NM,EVENT_NM,RENTLSPCE_BEGIN_DE,RENTLSPCE_END_DE,USE_DAY_CO,REQST_EVENT_NMPR_CO,EXCCLC_EVENT_NMPR_CO,ISE_ELSE_FLAG_NM
0,한얼광장,공공행사,제13회 베이징장애인올림픽대회 선전기원 2008 Friendly Festival,20080821,20080822,2,500.0,0.0,외부
1,88잔디마당,대중공연,2008 제2회 Let's Rock Festival,20080904,20080906,3,15000.0,0.0,외부
2,한얼광장,공공행사,기탁자는 기쁨을..이용자는 희망을! 2008 식품나눔행사,20081015,20081015,1,500.0,0.0,외부
3,올림픽홀,대중공연,큐반 올스타 콘서트,20081107,20081108,2,3000.0,0.0,내부
4,KSPO DOME(체조경기장),문화예술행사,플라시도 도밍고 내한공연,20090111,20090113,3,10000.0,0.0,내부
...,...,...,...,...,...,...,...,...,...
2060,뮤즈라이브,문화예술행사,BoA콘서트,20230306,20230312,7,6000.0,4504.0,내부
2061,핸드볼경기장,문화예술행사,2023 윤하 앵콜 콘서트,20230308,20230312,5,8000.0,9493.0,내부
2062,KSPO DOME(체조경기장),문화예술행사,해리 스타일스 내한공연 (HARRY STYLES LIVE IN SEOUL),20230313,20230320,8,14000.0,15100.0,내부
2063,평화의광장,공공행사,2023 서울마라톤 겸 동아마라톤,20230318,20230319,2,10000.0,10000.0,외부
2064,우리금융아트홀,대중공연,"마치,호영",20230325,20230326,2,1100.0,992.0,내부

df_2018

- 정렬 후 2018.12.01 ~ 데이터 추출

In [ ]:
df_2018 = df[df["RENTLSPCE_BEGIN_DE"] >= 20181201] # 2018-12-01 이후 df
df_2018

,FCLTY_NM,EVENT_SDIV_NM,EVENT_NM,RENTLSPCE_BEGIN_DE,RENTLSPCE_END_DE,USE_DAY_CO,REQST_EVENT_NMPR_CO,EXCCLC_EVENT_NMPR_CO,ISE_ELSE_FLAG_NM
1570,뮤즈라이브,문화예술행사,스트리머 뮤직 콘서트,20181201,20181201,1,210.0,210.0,내부
1572,K-아트홀,순수예술공연,연극 <그을린사랑>,20181203,20181216,14,350.0,1435.0,내부
1573,KSPO DOME(체조경기장),문화예술행사,2018 김동률 콘서트,20181203,20181209,7,33000.0,31525.0,내부
1574,우리금융아트홀,대중공연,최현우 <THE BRAIN>,20181204,20181231,28,26460.0,18604.0,내부
1575,핸드볼경기장,문화예술행사,2018 어반자카파 연말콘서트,20181205,20181210,6,6000.0,4778.0,내부
...,...,...,...,...,...,...,...,...,...
2060,뮤즈라이브,문화예술행사,BoA콘서트,20230306,20230312,7,6000.0,4504.0,내부
2061,핸드볼경기장,문화예술행사,2023 윤하 앵콜 콘서트,20230308,20230312,5,8000.0,9493.0,내부
2062,KSPO DOME(체조경기장),문화예술행사,해리 스타일스 내한공연 (HARRY STYLES LIVE IN SEOUL),20230313,20230320,8,14000.0,15100.0,내부
2063,평화의광장,공공행사,2023 서울마라톤 겸 동아마라톤,20230318,20230319,2,10000.0,10000.0,외부
2064,우리금융아트홀,대중공연,"마치,호영",20230325,20230326,2,1100.0,992.0,내부

데이터 내보내기

In [ ]:
df.to_csv("Olympic_rent.xlsx", index = False)

In [ ]:
df_2018.to_csv("Olympic_rent_2018.xlsx", index = False)